%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Shell (not callback): 
%                        10                                                                 
% 50 button 30 button 30 button 130 big_button 50
%                        10
%                    50 axes 50
%                        50
%                    50 axes 50
%                        50
%
%                                                  Written by Kim, Wiback,
%                                                        2017.03.15. v1.1.
%                                                        2017.03.18. v1.2.
%                                                        2017.03.20. v1.3.
%                                                        2017.03.21. v1.4.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%





%% Main Figures %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function varargout = GUI_figure(varargin)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
S = varargin{1};
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



%%%%%%%%%%%%%%%%%%%
% Upper most figure
%%%%%%%%%%%%%%%%%%%
screen_size = get(0, 'screensize');
fg_size = [950, 700];
S.fg = figure('units', 'pixels', ...
    'position', ...
    [(screen_size(3) - fg_size(1)) / 2, ... % 1/2*(Screen's x - figure's x)
    (screen_size(4) - fg_size(2)) / 2, ... % 1/2*(Screen's y - figure's y)
    fg_size(1), ... % The figure's x
    fg_size(2)], ... % The figure's y
    'menubar', 'none', ...
    'name','Fourier Analysis', ...
    'numbertitle', 'off', ...
    'resize', 'off');



%%%%%%
% Axes
%%%%%%

%%% Wave axes
S.ax_wav = axes('units', 'pixels', ...
    'position', [50, 375, 850, 275], ...
    'NextPlot', 'replacechildren');
title(S.ax_wav, 'Wave', 'fontsize', 15)
xlabel(S.ax_wav, '\fontsize{12}\color{red}samples')
ylabel(S.ax_wav, '\fontsize{12}\color{red}amplitude')

%%% Spectrum (or spectrogram) axes
S.ax_spec = axes('units', 'pixels', ...
    'position', [50, 50, 850, 275], ...
    'NextPlot', 'replacechildren');
title(S.ax_spec, 'Spectrogram', 'fontsize', 15)
xlabel(S.ax_spec, '\fontsize{12}\color{red}frequency')
ylabel(S.ax_spec, '\fontsize{12}\color{red}relative amp')



%%%%%%%%%
% Buttons
%%%%%%%%%

%%% Record button
S.pb_record = uicontrol('style', 'pushbutton', ...
    'units', 'pix', ...
    'position', [50, 660, 100, 30], ...
    'string', 'Record', ...
    'fontsize', 20, ...
    'ForegroundColor', 'red', ...
    'backgroundcolor', [0.7, 0.7, 0.7], ...
    'horizontalalign', 'center', ...
    'visible', 'on', ...
    'fontweight', 'bold');

%%% Play button (before)
S.pb_pbefore = uicontrol('style', 'pushbutton', ...
    'units', 'pix', ...
    'position', [180, 660, 100, 30], ...
    'string', 'Play b4', ...
    'fontsize', 20, ...
    'ForegroundColor', 'red', ...
    'backgroundcolor', [0.7, 0.7, 0.7], ...
    'horizontalalign', 'center', ...
    'visible', 'on', ...
    'enable', 'off', ...
    'fontweight', 'bold');

%%% Play button (after)
S.pb_pafter = uicontrol('style', 'pushbutton', ...
    'units', 'pix', ...
    'position', [310, 660, 100, 30], ...
    'string', 'Play after', ...
    'fontsize', 20, ...
    'ForegroundColor', 'red', ...
    'backgroundcolor', [0.7, 0.7, 0.7], ...
    'horizontalalign', 'center', ...
    'visible', 'on', ...
    'enable', 'off', ...
    'fontweight', 'bold');

%%% Reset button
S.pb_reset = uicontrol('style', 'pushbutton', ...
    'units', 'pix', ...
    'position', [540, 660, 360, 30], ...
    'string', 'Reset', ...
    'fontsize', 20, ...
    'ForegroundColor', 'red', ...
    'backgroundcolor', [0.7, 0.7, 0.7], ...
    'horizontalalign', 'center', ...
    'visible', 'on', ...
    'enable', 'off', ...
    'fontweight', 'bold');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
varargout{1} = S;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
end